BoxLayout:
    orientation: "vertical"

    Label:
        size_hint_y: 0.1
        text:"😎Menu principal😎"
        font_size: 30
    Label:
        size_hint_y:0.1
        text:"-Mano derecha: Grabar video\n -Mano Izquierda por 5 segundos: Sacar foto"
    CameraOpenCv:
        id: camera_menu
        size_hint_y: 0.6

    Button:
        size_hint_y:0.2
        text:"Ver imagenes"
        on_press:
            app.root.current = "archivos"


